baseURL = "https://sno.ws"
title = "Dan Snow"
languageCode = "en-US"
disableKinds = ["taxonomy", "term"]
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "The blog, photos, and book reviews of Dan Snow"
  author = "Dan Snow"
  photosURL = "https://content.sno.ws/photos"
  postURL = "https://content.sno.ws/posts"
  videoURL = "https://content.sno.ws/videos"
  heartSize = "0.75em"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "writing"
    name = "writing"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "reading"
    name = "reading"
    url = "/reading/"
    weight = 20

  [[menu.main]]
    identifier = "photos"
    name = "photos"
    url = "/photos/"
    weight = 30

  [[menu.main]]
    identifier = "talks"
    name = "talks"
    url = "/talks/"
    weight = 40

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 50

[permalinks]
  writing = "/:section/:year/:month/:day/:title/"
  reading = "/:section/:year/:month/:day/:title/"
  photos = "/:section/:year/:month/:day/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

[markup.goldmark.extensions]
  linkify = false

[outputs]
  home = ["HTML", "rss", "rssxsl"]

[outputFormats]
  [outputFormats.rssxsl]
    baseName = "index"
    mediaType = "application/xslt+xml"

[mediaTypes]
  [mediaTypes."application/xslt+xml"]
    suffixes = ["xsl"]